# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQT_sinuses.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(772, 587)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButtonPlot = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPlot.setEnabled(True)
        self.pushButtonPlot.setGeometry(QtCore.QRect(10, 470, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPlot.setFont(font)
        self.pushButtonPlot.setDefault(False)
        self.pushButtonPlot.setFlat(False)
        self.pushButtonPlot.setObjectName(_fromUtf8("pushButtonPlot"))
        self.groupBoxHarmonics = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxHarmonics.setGeometry(QtCore.QRect(230, 10, 221, 361))
        self.groupBoxHarmonics.setCheckable(False)
        self.groupBoxHarmonics.setObjectName(_fromUtf8("groupBoxHarmonics"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxHarmonics)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 331))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayoutHarmonics = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayoutHarmonics.setObjectName(_fromUtf8("gridLayoutHarmonics"))
        self.labelH6 = QtGui.QLabel(self.layoutWidget)
        self.labelH6.setObjectName(_fromUtf8("labelH6"))
        self.gridLayoutHarmonics.addWidget(self.labelH6, 4, 1, 1, 1)
        self.doubleSpinBoxHarm2 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm2.setDecimals(1)
        self.doubleSpinBoxHarm2.setObjectName(_fromUtf8("doubleSpinBoxHarm2"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm2, 0, 0, 1, 1)
        self.labelH2 = QtGui.QLabel(self.layoutWidget)
        self.labelH2.setObjectName(_fromUtf8("labelH2"))
        self.gridLayoutHarmonics.addWidget(self.labelH2, 0, 1, 1, 1)
        self.doubleSpinBoxHarm3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm3.setDecimals(1)
        self.doubleSpinBoxHarm3.setObjectName(_fromUtf8("doubleSpinBoxHarm3"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm3, 1, 0, 1, 1)
        self.labelH3 = QtGui.QLabel(self.layoutWidget)
        self.labelH3.setObjectName(_fromUtf8("labelH3"))
        self.gridLayoutHarmonics.addWidget(self.labelH3, 1, 1, 1, 1)
        self.doubleSpinBoxHarm4 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm4.setDecimals(1)
        self.doubleSpinBoxHarm4.setObjectName(_fromUtf8("doubleSpinBoxHarm4"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm4, 2, 0, 1, 1)
        self.labelH4 = QtGui.QLabel(self.layoutWidget)
        self.labelH4.setObjectName(_fromUtf8("labelH4"))
        self.gridLayoutHarmonics.addWidget(self.labelH4, 2, 1, 1, 1)
        self.doubleSpinBoxHarm5 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm5.setDecimals(1)
        self.doubleSpinBoxHarm5.setObjectName(_fromUtf8("doubleSpinBoxHarm5"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm5, 3, 0, 1, 1)
        self.labelH5 = QtGui.QLabel(self.layoutWidget)
        self.labelH5.setObjectName(_fromUtf8("labelH5"))
        self.gridLayoutHarmonics.addWidget(self.labelH5, 3, 1, 1, 1)
        self.doubleSpinBoxHarm6 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm6.setDecimals(1)
        self.doubleSpinBoxHarm6.setObjectName(_fromUtf8("doubleSpinBoxHarm6"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm6, 4, 0, 1, 1)
        self.doubleSpinBoxHarm7 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm7.setDecimals(1)
        self.doubleSpinBoxHarm7.setObjectName(_fromUtf8("doubleSpinBoxHarm7"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm7, 5, 0, 1, 1)
        self.labelH7 = QtGui.QLabel(self.layoutWidget)
        self.labelH7.setObjectName(_fromUtf8("labelH7"))
        self.gridLayoutHarmonics.addWidget(self.labelH7, 5, 1, 1, 1)
        self.doubleSpinBoxHarm8 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm8.setDecimals(1)
        self.doubleSpinBoxHarm8.setObjectName(_fromUtf8("doubleSpinBoxHarm8"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm8, 6, 0, 1, 1)
        self.labelH8 = QtGui.QLabel(self.layoutWidget)
        self.labelH8.setObjectName(_fromUtf8("labelH8"))
        self.gridLayoutHarmonics.addWidget(self.labelH8, 6, 1, 1, 1)
        self.doubleSpinBoxHarm9 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxHarm9.setDecimals(1)
        self.doubleSpinBoxHarm9.setObjectName(_fromUtf8("doubleSpinBoxHarm9"))
        self.gridLayoutHarmonics.addWidget(self.doubleSpinBoxHarm9, 7, 0, 1, 1)
        self.labelH9 = QtGui.QLabel(self.layoutWidget)
        self.labelH9.setObjectName(_fromUtf8("labelH9"))
        self.gridLayoutHarmonics.addWidget(self.labelH9, 7, 1, 1, 1)
        self.groupBoxStyle = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxStyle.setGeometry(QtCore.QRect(10, 10, 201, 361))
        self.groupBoxStyle.setObjectName(_fromUtf8("groupBoxStyle"))
        self.listWidgetStyles = QtGui.QListWidget(self.groupBoxStyle)
        self.listWidgetStyles.setGeometry(QtCore.QRect(10, 30, 181, 321))
        self.listWidgetStyles.setObjectName(_fromUtf8("listWidgetStyles"))
        self.checkBoxA = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxA.setGeometry(QtCore.QRect(480, 20, 171, 20))
        self.checkBoxA.setObjectName(_fromUtf8("checkBoxA"))
        self.groupBoxOffset = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxOffset.setGeometry(QtCore.QRect(470, 150, 281, 221))
        self.groupBoxOffset.setObjectName(_fromUtf8("groupBoxOffset"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBoxOffset)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 241, 191))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelTopText = QtGui.QLabel(self.layoutWidget1)
        self.labelTopText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTopText.setObjectName(_fromUtf8("labelTopText"))
        self.verticalLayout.addWidget(self.labelTopText)
        self.labelMidText = QtGui.QLabel(self.layoutWidget1)
        self.labelMidText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMidText.setObjectName(_fromUtf8("labelMidText"))
        self.verticalLayout.addWidget(self.labelMidText)
        self.Knob0 = Qwt5.QwtKnob(self.layoutWidget1)
        self.Knob0.setObjectName(_fromUtf8("Knob0"))
        self.verticalLayout.addWidget(self.Knob0)
        self.comboBoxAngCos = QtGui.QComboBox(self.centralwidget)
        self.comboBoxAngCos.setGeometry(QtCore.QRect(560, 90, 73, 22))
        self.comboBoxAngCos.setObjectName(_fromUtf8("comboBoxAngCos"))
        self.labelOffsetAs = QtGui.QLabel(self.centralwidget)
        self.labelOffsetAs.setGeometry(QtCore.QRect(480, 90, 53, 16))
        self.labelOffsetAs.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelOffsetAs.setObjectName(_fromUtf8("labelOffsetAs"))
        self.comboBoxCenter = QtGui.QComboBox(self.centralwidget)
        self.comboBoxCenter.setEnabled(True)
        self.comboBoxCenter.setGeometry(QtCore.QRect(70, 390, 161, 22))
        self.comboBoxCenter.setEditable(False)
        self.comboBoxCenter.setObjectName(_fromUtf8("comboBoxCenter"))
        self.labelPlot = QtGui.QLabel(self.centralwidget)
        self.labelPlot.setGeometry(QtCore.QRect(30, 390, 81, 20))
        self.labelPlot.setObjectName(_fromUtf8("labelPlot"))
        self.toolButton0 = QtGui.QToolButton(self.centralwidget)
        self.toolButton0.setGeometry(QtCore.QRect(700, 390, 41, 22))
        self.toolButton0.setObjectName(_fromUtf8("toolButton0"))
        self.progressBarDummy = QtGui.QProgressBar(self.centralwidget)
        self.progressBarDummy.setGeometry(QtCore.QRect(310, 390, 311, 23))
        self.progressBarDummy.setProperty("value", 24)
        self.progressBarDummy.setObjectName(_fromUtf8("progressBarDummy"))
        self.checkBoxB = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxB.setGeometry(QtCore.QRect(480, 50, 171, 17))
        self.checkBoxB.setObjectName(_fromUtf8("checkBoxB"))
        self.toolButton1 = QtGui.QToolButton(self.centralwidget)
        self.toolButton1.setGeometry(QtCore.QRect(640, 390, 41, 22))
        self.toolButton1.setObjectName(_fromUtf8("toolButton1"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionNew_window = QtGui.QAction(MainWindow)
        self.actionNew_window.setObjectName(_fromUtf8("actionNew_window"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.menuFile.addAction(self.actionNew_window)
        self.menuFile.addAction(self.actionClose)
        self.menuInfo.addAction(self.actionInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQT Sinuses", None))
        self.pushButtonPlot.setText(_translate("MainWindow", "Plot", None))
        self.groupBoxHarmonics.setTitle(_translate("MainWindow", "Sinusoidal Harmonics", None))
        self.labelH6.setText(_translate("MainWindow", "6th harmonic, %", None))
        self.labelH2.setText(_translate("MainWindow", "2nd harmonic, %", None))
        self.labelH3.setText(_translate("MainWindow", "3rd harmonic, %", None))
        self.labelH4.setText(_translate("MainWindow", "4th harmonic, %", None))
        self.labelH5.setText(_translate("MainWindow", "5th harmonic, %", None))
        self.labelH7.setText(_translate("MainWindow", "7th harmonic, %", None))
        self.labelH8.setText(_translate("MainWindow", "8th harmonic, %", None))
        self.labelH9.setText(_translate("MainWindow", "9th harmonic, %", None))
        self.groupBoxStyle.setTitle(_translate("MainWindow", "Line Style", None))
        self.checkBoxA.setText(_translate("MainWindow", "Draw black \"base\" sinus", None))
        self.groupBoxOffset.setTitle(_translate("MainWindow", "Offset", None))
        self.labelTopText.setText(_translate("MainWindow", "TopText", None))
        self.labelMidText.setText(_translate("MainWindow", "MidText", None))
        self.labelOffsetAs.setText(_translate("MainWindow", "Offset as", None))
        self.labelPlot.setText(_translate("MainWindow", "Plot: ", None))
        self.toolButton0.setText(_translate("MainWindow", "w", None))
        self.checkBoxB.setText(_translate("MainWindow", "Draw yellow \"phase-to-phase", None))
        self.toolButton1.setText(_translate("MainWindow", "...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuInfo.setTitle(_translate("MainWindow", "Info", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionNew_window.setText(_translate("MainWindow", "New window...", None))
        self.actionInfo.setText(_translate("MainWindow", "Info...", None))

from PyQt4 import Qwt5
